language: cpp
compiler:
  - gcc
env:
  - CXX_VERSION=4.8
  - CXX_VERSION=4.7
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo add-apt-repository -y ppa:fcitx-team/nightly
  - sudo add-apt-repository -y ppa:dns/gnu
  - sudo apt-get update
  - sudo apt-get install -y g++-${CXX_VERSION} autoconf-archive libboost-dev libleveldb-dev libsnappy-dev libevent-dev libthrift-dev thrift-compiler
  - sudo apt-get install -y libgflags-dev libgoogle-glog-dev protobuf-compiler libprotobuf-dev
  - export CXX="g++-${CXX_VERSION}"
  - sudo pip install cpp-coveralls --use-mirrors
before_script:
  - ./bootstrap
script:
  - export LD_LIBRARY_PATH=/usr/local/lib
  - CFLAGS='-g -O0' CXXFLAGS='-g -O0' ./configure --enable-gcov && make && make check
after_success:
  - cp vobla/.libs/libvobla_la-*.gc* vobla
  - if [[ $CXX == 'g++-4.7' ]]; then coveralls --gcov gcov-4.7 -e lib -e thrift -e glog-0.3.3; fi
notifications:
  email:
    recipients:
      - xulei82@gmail.com
      - zil.huang@gmail.com
    on_success: never
    on_failure: change
