#!/bin/sh -
#
# Re-generate ./configure and Makefile.in files.
#
# Copyright 2013 (c) Lei Xu <eddyxu@gmail.com>

set -e

if [ -d .git ]; then
	git submodule init
	git submodule update
	cp contrib/pre-commit .git/hooks
fi

case `uname` in
	Darwin*) glibtoolize --copy ;;  # For MacOSX
    *) libtoolize --copy ;; # Otherwise.
esac

autoheader
if [ -d /usr/local/share/aclocal ]; then
	aclocal -I m4 -I /usr/local/share/aclocal --install
else
	aclocal -I m4 --install
fi

autoconf

automake --foreign --add-missing --force-missing --copy

cd lib/vobla
./bootstrap && ./configure && make

cd ../
if [ ! -f gmock.zip ]; then
	wget -O gmock.zip https://googlemock.googlecode.com/files/gmock-1.7.0.zip
	unzip gmock.zip
	cd gmock-*
	./configure && make
fi
